// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhCAWlsHiVBiYjOhjdmCc-9DdEh3QM_c',
    appId: '1:497782311944:web:816a02d4e1fa1f57d595bd',
    messagingSenderId: '497782311944',
    projectId: 'hostelmate-f',
    authDomain: 'hostelmate-f.firebaseapp.com',
    storageBucket: 'hostelmate-f.firebasestorage.app',
    measurementId: 'G-9XSK55W9C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCreMmIrZ6pCYQvF-OQC00HLvMs757iBwQ',
    appId: '1:497782311944:android:44a2ec34f510177ad595bd',
    messagingSenderId: '497782311944',
    projectId: 'hostelmate-f',
    storageBucket: 'hostelmate-f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaySiu6YjMAZK7bkAJlPu9ghWLySzScao',
    appId: '1:497782311944:ios:c04a1f7c3b34e559d595bd',
    messagingSenderId: '497782311944',
    projectId: 'hostelmate-f',
    storageBucket: 'hostelmate-f.firebasestorage.app',
    iosBundleId: 'com.example.hostelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaySiu6YjMAZK7bkAJlPu9ghWLySzScao',
    appId: '1:497782311944:ios:c04a1f7c3b34e559d595bd',
    messagingSenderId: '497782311944',
    projectId: 'hostelmate-f',
    storageBucket: 'hostelmate-f.firebasestorage.app',
    iosBundleId: 'com.example.hostelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALhCAWlsHiVBiYjOhjdmCc-9DdEh3QM_c',
    appId: '1:497782311944:web:fc3a8594da9ec927d595bd',
    messagingSenderId: '497782311944',
    projectId: 'hostelmate-f',
    authDomain: 'hostelmate-f.firebaseapp.com',
    storageBucket: 'hostelmate-f.firebasestorage.app',
    measurementId: 'G-MYTXV8BDF0',
  );
}
